owner: MePhew-GonteQ-Industries
repo: zolza-hairstyles-uptime

sites:
  - name: Zołza Hairstyles
    url: https://zolza-hairstyles.pl
  - name: API
    url: https://api.zolza-hairstyles.pl/api/docs

status-website:
  baseUrl: /zolza-hairstyles-uptime
  # favicon: 
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Zołza Hairstyles Status
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
      
  user-agent: $OWNER
