owner: MePhew-GonteQ-Industries
repo: zolza-hairstyles-uptime

sites:
  - name: Zołza Hairstyles
    url: https://zolza-hairstyles.pl
  - name: API
    url: https://api.zolza-hairstyles.pl/api/docs
    icon: https://raw.githubusercontent.com/MePhew-GonteQ-Industries/zolza-hairstyles-uptime/master/assets/server.svg

status-website:
  baseUrl: /zolza-hairstyles-uptime
  favicon: https://raw.githubusercontent.com/MePhew-GonteQ-Industries/zolza-hairstyles-uptime/master/assets/favicon.ico
  logoUrl: https://raw.githubusercontent.com/MePhew-GonteQ-Industries/zolza-hairstyles-uptime/master/assets/android-chrome-192x192.png
  name: Zołza Hairstyles Status
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
      
  user-agent: $OWNER
